horseornot/horseornot/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('horses.urls', namespace='horses')),
    url(r'^admin/', include(admin.site.urls)),
]

horseornot/horses/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^submit/(?P<profile_id>[0-9]+)$', views.submit, name='submit'),
]

horseornot/horses/models.py
from django.db import models


class Horse(models.Model):
    name = models.CharField(max_length=50)
    real_profile = models.CharField(max_length=30)
    horse_profile = models.CharField(max_length=30)

    def __str__(self):
        return self.name


# Create your models here.

horseornot/horses/views.py
import random

from django.contrib import messages
from django.core.urlresolvers import reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template import RequestContext, loader

from .models import Horse


def index(request):
    template = loader.get_template('horses/display.html')

    try:
        horse = Horse.objects.order_by('?')[0]
        field = random.choice(['real_profile', 'horse_profile'])
        data = getattr(horse, field)
        context = {
            'horse': horse,
            'content': data,
        }
    except IndexError:
        context = {}

    return render(request, 'horses/display.html', context)

def display_horse(request, profile_id):
    horse = Horse.objects.get(pk=profile_id)
    fields = ['real_profile', 'horse_profile']

    return HttpResponse(getattr(horse, random.choice(fields)))

def submit(request, profile_id):
    if request.POST['profile_pick'] == request.POST['profile']:
        message = 'Correct'
    else:
        message = 'Wrong'

    messages.info(request, message)

    return HttpResponseRedirect(reverse('horses:index'))

horseornot/horses/templates/horses/display.html
{% if horse %}
{% if messages %}
{% for message in messages %}
<p>{{ message }}</p>
{% endfor %}
{% endif %}
<p>{{ horse.name }}</p>
<p>{{ content }}</p>
<form action="{% url 'horses:submit' horse.id %}" method="post">
    {% csrf_token %}
    <input type="hidden" name="profile" value="{{content}}" />
    <p><input type="radio" name="profile_pick" id="real" value="real" />
    <label for="real">{{ horse.real_profile }}</label></p>
    <p><input type="radio" name="profile_pick" id="horse" value="horse" />
    <label for="horse">{{ horse.horse_profile }}</label></p>
    <input type="submit" value="Submit" />
</form>
{% else %}
<p>No horse</p>
{% endif %}